#!/usr/bin/env node
import { access, cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * Assemble everything the Windows installer ships, into one directory.
 *
 * Inno Setup only knows how to compress a folder; deciding *what goes in it* is
 * this script's job, and it is the step most likely to go quietly wrong — a
 * renamed file still builds a perfectly valid installer that fails on the
 * user's machine. So this refuses to stage an incomplete payload rather than
 * producing one, and `test/installer.test.mjs` checks the result against the
 * file list the .iss actually references.
 *
 *     node installer/stage.mjs --node C:\\path\\to\\node.exe
 *
 * `--node` is optional here and required in CI: without it the payload is
 * complete except for the runtime, which is what lets this run — and be
 * tested — on a machine that is not Windows.
 */

const HERE = dirname(fileURLToPath(import.meta.url));
const PORT = join(HERE, "..");
const HARNESS = join(PORT, "..", "ego-browser", "dist", "out");
const LOCKFILE = join(PORT, "package-lock.json");

/**
 * The install tree mirrors the monorepo, because `bin/ego-browser.mjs` resolves
 * the harness as `../../ego-browser/dist/out/index.js`. Flattening it would
 * mean passing `--sdk-path` on every invocation; mirroring costs two directory
 * levels and no code change at all.
 */
const LAYOUT = [
  {
    from: join(HARNESS, "index.js"),
    to: join("package", "ego-browser", "dist", "out", "index.js"),
    why: "the agent runtime the port drives",
  },
  {
    from: join(HARNESS, "ego-browser"),
    to: join("package", "ego-browser", "dist", "out", "ego-browser"),
    why: "the skill package the runtime reads learnings and helpers from",
  },
  {
    from: join(PORT, "bin"),
    to: join("package", "ego-linux", "bin"),
    why: "the CLI itself",
  },
  {
    from: join(PORT, "src"),
    to: join("package", "ego-linux", "src"),
    why: "the port's modules",
  },
  {
    from: join(PORT, "assets"),
    to: join("package", "ego-linux", "assets"),
    why: "the icon the shortcut and the uninstaller draw",
  },
  {
    from: join(PORT, "package.json"),
    to: join("package", "ego-linux", "package.json"),
    why: "declares the tree ESM, without which node refuses every import",
  },
  {
    from: LOCKFILE,
    to: join("package", "ego-linux", "package-lock.json"),
    why: "records the exact MCP runtime dependency graph",
  },
];

/**
 * The command that ends up on PATH.
 *
 * `%~dp0` is the shim's own directory with a trailing separator, so the whole
 * install is relocatable and nothing needs an absolute path baked in. cmd
 * propagates the last command's exit code by itself, and passes stdin straight
 * through — which is the entire point, since every invocation is a heredoc.
 */
const SHIM = [
  "@echo off",
  "rem Generated by installer/stage.mjs -- edit that, not this.",
  '"%~dp0node\\node.exe" "%~dp0package\\ego-linux\\bin\\ego-browser.mjs" %*',
  "",
].join("\r\n");

const MCP_SHIM = [
  "@echo off",
  "rem Generated by installer/stage.mjs -- edit that, not this.",
  '"%~dp0node\\node.exe" "%~dp0package\\ego-linux\\bin\\ego-browser-mcp.mjs" %*',
  "",
].join("\r\n");

async function exists(target) {
  try {
    await access(target, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

/** Every file under a staged payload, as forward-slashed relative paths. */
async function manifest(dir) {
  const { readdir } = await import("node:fs/promises");
  const found = [];
  async function walk(current) {
    for (const entry of await readdir(current, { withFileTypes: true })) {
      const path = join(current, entry.name);
      if (entry.isDirectory()) await walk(path);
      else found.push(relative(dir, path).split(sep).join("/"));
    }
  }
  await walk(dir);
  return found.sort();
}

/** Copy only lockfile-marked production dependencies into the installer. */
async function stageProductionDependencies(payload) {
  const lock = JSON.parse(await readFile(LOCKFILE, "utf8"));
  const packagePaths = Object.entries(lock.packages || {})
    .filter(
      ([path, metadata]) =>
        path.startsWith("node_modules/") && metadata?.dev !== true,
    )
    .map(([path]) => path);
  if (packagePaths.length === 0) {
    throw new Error(`no production dependencies found in ${LOCKFILE}`);
  }

  for (const path of packagePaths) {
    const from = join(PORT, path);
    if (!(await exists(from))) {
      throw new Error(`missing ${from} — run npm ci in ${PORT}`);
    }
    const target = join(payload, "package", "ego-linux", path);
    await mkdir(dirname(target), { recursive: true });
    await cp(from, target, { recursive: true });
  }
}

export async function stage({ out, nodeExe = null } = {}) {
  const payload = out || join(HERE, "payload");

  if (!(await exists(join(HARNESS, "index.js")))) {
    throw new Error(
      `the harness is not built: ${join(HARNESS, "index.js")} is missing.\n` +
        `Run: cd ../ego-browser && CI=true npm ci && npm run build`,
    );
  }

  await rm(payload, { recursive: true, force: true });
  await mkdir(payload, { recursive: true });

  for (const { from, to, why } of LAYOUT) {
    if (!(await exists(from))) {
      throw new Error(`missing ${from} — ${why}`);
    }
    const target = join(payload, to);
    await mkdir(dirname(target), { recursive: true });
    await cp(from, target, { recursive: true });
  }

  await stageProductionDependencies(payload);

  await writeFile(join(payload, "ego-browser.cmd"), SHIM);
  await writeFile(join(payload, "ego-browser-mcp.cmd"), MCP_SHIM);

  if (nodeExe) {
    if (!(await exists(nodeExe))) {
      throw new Error(`--node points at nothing: ${nodeExe}`);
    }
    await mkdir(join(payload, "node"), { recursive: true });
    await cp(nodeExe, join(payload, "node", "node.exe"));
  }

  const version = JSON.parse(
    await readFile(join(PORT, "package.json"), "utf8"),
  ).version;

  return {
    payload,
    version,
    files: await manifest(payload),
    bundledNode: Boolean(nodeExe),
  };
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(process.argv[1]).href
) {
  const argv = process.argv.slice(2);
  const at = argv.indexOf("--node");
  const nodeExe = at === -1 ? null : argv[at + 1];
  const outAt = argv.indexOf("--out");
  const out = outAt === -1 ? undefined : argv[outAt + 1];

  const result = await stage({ out, nodeExe });
  process.stdout.write(
    `staged ${result.files.length} files into ${result.payload}\n` +
      `version ${result.version}\n` +
      (result.bundledNode
        ? "node runtime bundled\n"
        : "NO node runtime bundled — pass --node <path to node.exe> for a shippable installer\n"),
  );
}
