[CmdletBinding()]
param(
  [string]$BinDir = (Join-Path $env:LOCALAPPDATA "Programs\ego-lite\bin"),
  [switch]$NoDoctor
)

$ErrorActionPreference = "Stop"

function Invoke-Checked {
  param(
    [Parameter(Mandatory = $true)][string]$Command,
    [Parameter(Mandatory = $true)][string[]]$Arguments
  )

  & $Command @Arguments
  if ($LASTEXITCODE -ne 0) {
    throw "$Command failed with exit code $LASTEXITCODE"
  }
}

if ($env:OS -ne "Windows_NT") {
  throw "install-windows.ps1 supports native Windows only"
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = (Resolve-Path (Join-Path $scriptDir "..\..\..")).Path
$harness = Join-Path $repoRoot "package/ego-browser"
$port = Join-Path $repoRoot "package/ego-linux"
$cli = Join-Path $port "bin\ego-browser.mjs"
$mcpCli = Join-Path $port "bin\ego-browser-mcp.mjs"

if (-not (Test-Path $cli)) {
  throw "cannot find the Windows port at $cli"
}
if (-not (Test-Path $mcpCli)) {
  throw "cannot find the MCP server at $mcpCli"
}

$nodeCommand = Get-Command node.exe -ErrorAction SilentlyContinue
$npmCommand = Get-Command npm.cmd -ErrorAction SilentlyContinue
if (-not $nodeCommand -or -not $npmCommand) {
  throw "Node.js 22 or newer and npm are required. Install Node.js, open a new PowerShell, and retry."
}

$nodeVersion = (& $nodeCommand.Source --version).Trim()
if ($LASTEXITCODE -ne 0) {
  throw "node --version failed with exit code $LASTEXITCODE"
}
$nodeMajor = [int]($nodeVersion.TrimStart("v").Split(".")[0])
if ($nodeMajor -lt 22) {
  throw "Node.js 22 or newer is required; found $nodeVersion"
}

Write-Host "Building ego-browser harness..."
Push-Location $harness
try {
  Invoke-Checked -Command $npmCommand.Source -Arguments @("ci", "--ignore-scripts")
  Invoke-Checked -Command $npmCommand.Source -Arguments @("run", "build")
}
finally {
  Pop-Location
}

Write-Host "Installing MCP runtime dependencies..."
Push-Location $port
try {
  Invoke-Checked -Command $npmCommand.Source -Arguments @("ci", "--omit=dev", "--ignore-scripts")
}
finally {
  Pop-Location
}

New-Item -ItemType Directory -Force -Path $BinDir | Out-Null
$shimPath = Join-Path $BinDir "ego-browser.cmd"
$shim = @(
  "@echo off",
  "rem Generated by install-windows.ps1 -- rerun the installer after moving the checkout.",
  ('"{0}" "{1}" %*' -f $nodeCommand.Source, $cli),
  ""
) -join "`r`n"
[IO.File]::WriteAllText(
  $shimPath,
  $shim,
  [Text.UTF8Encoding]::new($false)
)
$mcpShimPath = Join-Path $BinDir "ego-browser-mcp.cmd"
$mcpShim = @(
  "@echo off",
  "rem Generated by install-windows.ps1 -- rerun the installer after moving the checkout.",
  ('"{0}" "{1}" %*' -f $nodeCommand.Source, $mcpCli),
  ""
) -join "`r`n"
[IO.File]::WriteAllText(
  $mcpShimPath,
  $mcpShim,
  [Text.UTF8Encoding]::new($false)
)

$userPath = [Environment]::GetEnvironmentVariable("Path", "User")
$entries = @($userPath -split ";" | Where-Object { $_ })
$alreadyOnPath = $entries | Where-Object {
  $_.TrimEnd("\") -ieq $BinDir.TrimEnd("\")
}
if (-not $alreadyOnPath) {
  $newUserPath = (@($entries) + $BinDir) -join ";"
  [Environment]::SetEnvironmentVariable("Path", $newUserPath, "User")
}
if (-not (($env:Path -split ";") -contains $BinDir)) {
  $env:Path = "$BinDir;$env:Path"
}

if (-not $NoDoctor) {
  Write-Host "Running installation diagnostics..."
  Invoke-Checked -Command $shimPath -Arguments @("--doctor")
}

Write-Host ""
Write-Host "ego-browser installed natively for Windows: $shimPath"
Write-Host "ego-browser MCP server installed: $mcpShimPath"
Write-Host "Open a new PowerShell before using it from another terminal."
Write-Host "Optional: ego-browser --install-desktop-entry"
